server:
  port: 8090

spring:
  application:
    name: smart-fridge-api

  datasource:
    url: jdbc:postgresql://localhost:5432/smart_fridge_db
    username: ${DB_USERNAME:smart_fridge_user}
    password: ${DB_PASSWORD:smart_fridge_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.smartfridge: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

notification:
  email:
    from: nik.tukhashvili@makingscience.com
    to: n_tukhashvili4@cu.edu.ge